name: Publish Image to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_build:
    name: Build And Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Commit Hash
        id: get_commit_hash
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Version
        id: get_version
        run: echo "version=$(cat ci/version)" >> $GITHUB_ENV

      - name: Get Build Number
        id: get_build_number
        run: echo "build_number=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Debug - Print Variables
        run: |
          echo "Version: ${{ env.version }}"
          echo "Build Number: ${{ env.build_number }}"
          echo "Commit Hash: ${{ env.commit_hash }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean install
        working-directory: .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ci/Dockerfile
          push: true
          tags: |
            raphaeleze/recipex:${{ env.version }}
            raphaeleze/recipex:${{ env.version }}-${{ env.commit_hash }}
            raphaeleze/recipex:${{ env.version }}-${{ env.commit_hash }}-${{ env.build_number }}

      # Note: Ideally, we would push the Docker image to Amazon ECR (Elastic Container Registry).
      #
      # The following commented-out steps show how you would do this:
      #
      # - name: Authenticate Docker to Amazon ECR
      #   run: |
      #     aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      #
      # - name: Tag Docker Image for ECR
      #   run: |
      #     docker tag $IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
      #
      # - name: Push Docker Image to ECR
      #   run: |
      #     docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
      #
      # However, to avoid incurring additional AWS costs, we are currently using Docker Hub for image storage and distribution.
